const createApi = `${process.env.NEXT_PUBLIC_BASE_API_URL}/api/`;
export const endPoints = {
  test: `${createApi}test`,
  login: `${createApi}admin/login`,
  sideBarData: `${createApi}admin/dashboard`,
  getOrgType: `${createApi}OrgSetup/GetType`,
  addOrg: `${createApi}OrgSetup/AddOrg`,
  orgList: `${createApi}OrgSetup/OrgList`,
  getOrgDetails: (id) => `${createApi}OrgSetup/CheckFinYear/${id}`,
  addOrgBranch: `${createApi}OrgSetup/MapBranch`,
  getOrgBranchList: (id) => `${createApi}OrgSetup/GetBranch/${id}`,
  getModuleType: `${createApi}OrgSetup/GetModule`,
  getOrgModuleList: `${createApi}OrgSetup/GetListOrgModule`,
  addModule: `${createApi}OrgSetup/AddModule`,
  addFinancialYear: `${createApi}OrgSetup/AddFinancialYear`,
  addRentalData: `${createApi}OrgSetup/AddRentelData`,
  addOrgAdminUser: `${createApi}OrgSetup/AddOrgAdminUser`,
  addSmsData: `${createApi}OrgSetup/AddSMSData`,
  getHeadData: `${createApi}OrgSetup/GetOrgAccountHead`,
  addAccountSubHead: `${createApi}OrgSetup/AddOrgAcctSubHead`,
  getAccountSubHeadData: `${createApi}OrgSetup/GetOrgAcctSubHead`,
  getAccountLedgerData: `${createApi}OrgSetup/GetorgAcctLedger`,
  addAccountLedger: `${createApi}OrgSetup/AddOrgAcctLedger`,
  getMemberTypeData: `${createApi}OrgSetup/GetMemberType`,
  getMemberGlData: (type) => `${createApi}OrgSetup/GetMemberGL/${type}`,
  addShareProduct: `${createApi}OrgSetup/AddShareProduct`,
  getDepositProductType: `${createApi}OrgSetup/GetDeposit/ProductType`,
  getDepositType: `${createApi}OrgSetup/GetDeposit/DepositType`,
  getDepositGlData: (type) =>
    `${createApi}OrgSetup/GetDeposit/AccountGl/${type}`,
  addDepositProduct: `${createApi}OrgSetup/DepositProduct/AddProduct`,
  getDepositProductData: `${createApi}OrgSetup/DepositProduct/GetProdList`,
  getCheckDepositModule: (id) =>
    `${createApi}OrgSetup/DepositProduct/CheckModule/${id}`,
  getMapDepositInttTypeData: `${createApi}OrgSetup/DepositProduct/GetInttType`,
  getMapDepositDurationUnitData: `${createApi}OrgSetup/DepositProduct/GetDurUnit`,
  getMapDepositFineOnData: `${createApi}OrgSetup/DepositProduct/GetFineOn`,
  addMapDepositProductData: `${createApi}OrgSetup/DepositProduct/MapOrgDepositProduct`,
  getLoanProductTypeData: `${createApi}OrgSetup/LoanProduct/GetProductType`,
  getLoanProductGlData: (type) =>
    `${createApi}OrgSetup/LoanProduct/AccountGl/${type}`,
  addLoanProduct: `${createApi}OrgSetup/LoanProduct/AddProduct`,
  getLoanProductData: `${createApi}OrgSetup/LoanProduct/GetProdList`,
  getCheckLoanModule: (id) =>
    `${createApi}OrgSetup/LoanProduct/CheckModule/${id}`,
  getMapLoanRepayTypeData: `${createApi}OrgSetup/LoanProduct/GetRepayType`,
  getMapLoanDurUnitData: `${createApi}OrgSetup/LoanProduct/GetDurUnit`,
  getMapLoanOverdueOnData: `${createApi}OrgSetup/LoanProduct/GetOverdueOn`,
  getMapLoanGraceOnData: `${createApi}OrgSetup/LoanProduct/GetGraceOn`,
  getMapLoanDepositProductData: (id) =>
    `${createApi}OrgSetup/LoanProduct/GetDepositProd/${id}`,
  addMapLoanProduct: `${createApi}OrgSetup/LoanProduct/MapProduct`,
  addUser: `${createApi}admin/AddUser`,
  changeUsePassword: `${createApi}admin/ChangeUserPassword`,
  getRoleList: `${createApi}admin/AssignRoleList`,
  getRoleAssignUser: `${createApi}admin/GetRoleAsignUserList`,
  addAdminModule: `${createApi}admin/AssignAdminModule`,
  logout: `${createApi}admin/logout`,
};
